services:
  # A Docker web service
  - type: web
    name: langflow
    runtime: docker
    dockerfilePath: ./docker/render.pre-release.Dockerfile
    repo: https://github.com/langflow-ai/langflow
    branch: dev
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: LANGFLOW_DATABASE_URL
        value: sqlite:////home/user/.cache/langflow/langflow.db
    disk:
      name: langflow-data
      mountPath: /home/user/.cache/langflow
