name: lint

on:
  push:
    branches: [main]
    paths:
      - "poetry.lock"
      - "pyproject.toml"
      - "src/backend/**"
  pull_request:
    paths:
      - "poetry.lock"
      - "pyproject.toml"
      - "src/backend/**"

env:
  POETRY_VERSION: "1.8.2"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} + Poetry ${{ env.POETRY_VERSION }}
        uses: "./.github/actions/poetry_caching"
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ env.POETRY_VERSION }}
          cache-key: ${{ runner.os }}-poetry-${{ env.POETRY_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install Python dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install
      - name: Get .mypy_cache to speed up mypy
        uses: actions/cache@v4
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MIN: "2"
        with:
          path: |
            ./.mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('**/pyproject.toml') }}
      - name: Lint check
        run: |
          make lint
